--Add these to your Existing vehicles.lua in qb-core/shared/vehicles.lua
--NOTE: You should check ALL of the prices and set them all to what you want them to be
--NOTE: You should also set the SHOP on each car as well. 

  --- ACURA
	['tltypes'] = {
		['name'] = 'Acura TL Type-S',
		['brand'] = 'Acura',
		['model'] = 'tltypes',
		['price'] = 40000,
		['category'] = 'sedans',
		['hash'] = 'tltypes',
		['shop'] = 'pdm',
	},
	--- Astonmartin
	['amdbx'] = {
		['name'] = 'DBX Carbon Edition',
		['brand'] = 'Aston Martin',
		['model'] = 'amdbx',
		['price'] = 13000,
		['category'] = 'suvs',
		['hash'] = 'amdbx',
		['shop'] = 'pdm',
	},
	['ast'] = {
		['name'] = '2013 Vanquish',
		['brand'] = 'Aston Martin',
		['model'] = 'ast',
		['price'] = 20000,
		['category'] = 'coupes',
		['hash'] = 'ast',
		['shop'] = 'pdm',
	},
	--- Audi
	['80B4'] = {
		['name'] = 'Cabriolet RS2 B4',
		['brand'] = 'Audi',
		['model'] = '80B4',
		['price'] = 8000,
		['category'] = 'sportsclassics',
		['hash'] = '80B4',
		['shop'] = 'pdm',
	},
	['aaq4'] = {
		['name'] = '17 A4 Quattro ABT',
		['brand'] = 'Audi',
		['model'] = 'aaq4',
		['price'] = 9000,
		['category'] = 'sports',
		['hash'] = 'aaq4',
		['shop'] = 'pdm',
	},
	['audquattros'] = {
		['name'] = '83 Quattro Sport',
		['brand'] = 'Audi',
		['model'] = 'audquattros',
		['price'] = 12000,
		['category'] = 'sportsclassics',
		['hash'] = 'audquattros',
		['shop'] = 'pdm',
	},
	['q820'] = {
		['name'] = '20 Q8 50TDI',
		['brand'] = 'Audi',
		['model'] = 'q820',
		['price'] = 12000,
		['category'] = 'suvs',
		['hash'] = 'q820',
		['shop'] = 'pdm',
	},
	['r820'] = {
		['name'] = '20 R8',
		['brand'] = 'Audi',
		['model'] = 'r820',
		['price'] = 7000,
		['category'] = 'super',
		['hash'] = 'r820',
		['shop'] = 'pdm',
	},
	['r8ppi'] = {
		['name'] = '13 R8 V10',
		['brand'] = 'Audi',
		['model'] = 'r8ppi',
		['price'] = 5000,
		['category'] = 'sports',
		['hash'] = 'r8ppi',
		['shop'] = 'pdm',
	},
	['rs6'] = {							
		['name'] = '16 RS6 C7',
		['brand'] = 'Audi',
		['model'] = 'rs6',
		['price'] = 80000,
		['category'] = 'super',
		['hash'] = 'rs6',
		['shop'] = 'pdm',
	},
	['rs72020'] = {
		['name'] = '20 RS7',
		['brand'] = 'Audi',
		['model'] = 'rs72020',
		['price'] = 80000,
		['category'] = 'sedans',
		['hash'] = 'rs72020',
		['shop'] = 'pdm',
	},
	['s8d2'] = {
		['name'] = '98 S8 D2 PFL',
		['brand'] = 'Audi',
		['model'] = 's8d2',
		['price'] = 80000,
		['category'] = 'sedans',
		['hash'] = 's8d2',
		['shop'] = 'pdm',
	},
	['sq72016'] = {
		['name'] = '16 SQ7',
		['brand'] = 'Audi',
		['model'] = 'sq72016',
		['price'] = 3200,
		['category'] = 'suvs',
		['hash'] = 'sq72016',
		['shop'] = 'pdm',
	},
	['ttrs'] = {
		['name'] = '10 TT RS',
		['brand'] = 'Audi',
		['model'] = 'ttrs',
		['price'] = 30000,
		['category'] = 'sports',
		['hash'] = 'ttrs',
		['shop'] = 'pdm',
	},
	--Bentley
	['bbentayga'] = {
		['name'] = 'Bentayga',
		['brand'] = 'Bentley',
		['model'] = 'bbentayga',
		['price'] = 10000,
		['category'] = 'suvs',
		['hash'] = 'bbentayga',
		['shop'] = 'luxury',
	},
	['cgts'] = {
		['name'] = '20 Continental GT Conv',
		['brand'] = 'Bentley',
		['model'] = 'cgts',
		['price'] = 12000,
		['category'] = 'sports',
		['hash'] = 'cgts',
		['shop'] = 'luxury',
	},
	--BMW
	['760li04'] = {
		['name'] = '04 760LI',
		['brand'] = 'BMW',
		['model'] = '760li04',
		['price'] = 9000,
		['category'] = 'sedans',
		['hash'] = '760li04',
		['shop'] = 'luxury',
	},
	['bmci'] = {
		['name'] = 'bmci',
		['brand'] = 'BMW',
		['model'] = 'bmci',
		['price'] = 30000,
		['category'] = 'sports',
		['hash'] = 'bmci',
		['shop'] = 'luxury',
	},
	['e34'] = {
		['name'] = '95 M5 E34',
		['brand'] = 'BMW',
		['model'] = 'e34',
		['price'] = 40000,
		['category'] = 'sedans',
		['hash'] = 'e34',
		['shop'] = 'luxury',
	},
	['i8'] = {
		['name'] = 'i8',
		['brand'] = 'BMW',
		['model'] = 'i8',
		['price'] = 32500,
		['category'] = 'super',
		['hash'] = 'i8',
		['shop'] = 'luxury',
	},
	['m2'] = {
		['name'] = '2016 M2',
		['brand'] = 'BMW',
		['model'] = 'm2',
		['price'] = 31000,
		['category'] = 'sports',
		['hash'] = 'm2',
		['shop'] = 'luxury',
	},
	['m3e36'] = {
		['name'] = '08 M3 E36',
		['brand'] = 'BMW',
		['model'] = 'm3e36',
		['price'] = 37000,
		['category'] = 'sports',
		['hash'] = 'm3e36',
		['shop'] = 'luxury',
	},
	['m3e92'] = {
		['name'] = '08 M3 e92',
		['brand'] = 'BMW',
		['model'] = 'm3e92',
		['price'] = 19000,
		['category'] = 'sports',
		['hash'] = 'm3e92',
		['shop'] = 'luxury',
	},
	['m3f80'] = {
		['name'] = '15 M3 F80',
		['brand'] = 'BMW',
		['model'] = 'm3f80',
		['price'] = 22000,
		['category'] = 'sedans',
		['hash'] = 'm3f80',
		['shop'] = 'luxury',
	},
	['m4f82'] = {
		['name'] = '15 M4 F82',
		['brand'] = 'BMW',
		['model'] = 'm4f82',
		['price'] = 28000,
		['category'] = 'coupes',
		['hash'] = 'm4f82',
		['shop'] = 'luxury',
	},
	['m6f13'] = {
		['name'] = 'M6 F13 Shadow Line',
		['brand'] = 'BMW',
		['model'] = 'm6f13',
		['price'] = 30000,
		['category'] = 'coupes',
		['hash'] = 'm6f13',
		['shop'] = 'luxury',
	},
	['x5e53'] = {
		['name'] = 'X5 E53',
		['brand'] = 'BMW',
		['model'] = 'x5e53',
		['price'] = 33000,
		['category'] = 'suvs',
		['hash'] = 'x5e53',
		['shop'] = 'luxury',
	},
	['x6m'] = {
		['name'] = 'X6 M',
		['brand'] = 'BMW',
		['model'] = 'x6m',
		['price'] = 27000,
		['category'] = 'suvs',
		['hash'] = 'x6m',
		['shop'] = 'luxury',
	},
	['z419'] = {
		['name'] = '19 Z4 M40i',
		['brand'] = 'BMW',
		['model'] = 'z419',
		['price'] = 34000,
		['category'] = 'sports',
		['hash'] = 'z419',
		['shop'] = 'luxury',
	},
	--[BUGATTI]/bolide
	['bolide'] = {
		['name'] = 'bolide',
		['brand'] = 'BUGATTI',
		['model'] = 'bolide',
		['price'] = 22000,
		['category'] = 'super',
		['hash'] = 'bolide',
		['shop'] = 'luxury',
	},
	--Cadillac
	['cats'] = {
		['name'] = 'ATS V Coupe',
		['brand'] = 'Cadillac',
		['model'] = 'cats',
		['price'] = 28000,
		['category'] = 'sports',
		['hash'] = 'cats',
		['shop'] = 'luxury',
	},
	['cesc21'] = {			
		['name'] = '21 Escalade',
		['brand'] = 'Cadillac',
		['model'] = 'cesc21',
		['price'] = 149000,
		['category'] = 'suvs',
		['hash'] = 'cesc21',
		['shop'] = 'luxury',
	},
	--chevrolet
	['09tahoe'] = {		
		['name'] = '09 Tahoe',
		['brand'] = 'chevrolet',
		['model'] = '09tahoe',
		['price'] = 205000,
		['category'] = 'suvs',
		['hash'] = '09tahoe',
		['shop'] = 'luxury',
	},
	['15tahoe'] = { 	 	
		['name'] = '15 Tahoe',
		['brand'] = 'chevrolet',
		['model'] = '15tahoe',
		['price'] = 1120000,
		['category'] = 'suvs',
		['hash'] = '15tahoe',
		['shop'] = 'luxury',
	},
	['2020ss'] = { 	 	
		['name'] = '20 Camaro SS',
		['brand'] = 'chevrolet',
		['model'] = '2020ss',
		['price'] = 1350000,
		['category'] = 'sports',
		['hash'] = '2020ss',
		['shop'] = 'luxury',
	},
	['camrs17'] = {
		['name'] = '17 Camaro RS',
        	['brand'] = 'chevrolet',
		['model'] = 'camrs17',
		['price'] = 160,
		['category'] = 'muscle',
		['hash'] = 'camrs17',
		['shop'] = 'luxury',
	},
	['tahoe21'] = {
		['name'] = '21 Tahoe RST',
        	['brand'] = 'chevrolet',
		['model'] = 'tahoe21',
		['price'] = 510,
		['category'] = 'suvs',
		['hash'] = 'tahoe21',
		['shop'] = 'luxury',
	},
	--corvette
	['c7'] = {
		['name'] = '14 C7 Stingray',
        	['brand'] = 'corvette',
		['model'] = 'c7',
		['price'] = 225000,
		['category'] = 'super',
		['hash'] = 'c7',
		['shop'] = 'luxury',
	},
	['corvettec5z06'] = {
		['name'] = 'C5 Z06',
        	['brand'] = 'corvette',
		['model'] = 'corvettec5z06',
		['price'] = 280000,
		['category'] = 'sports',
		['hash'] = 'corvettec5z06',
		['shop'] = 'luxury',
	},
	['czr1'] = {
		['name'] = '09 ZR1',
        	['brand'] = 'corvette',
		['model'] = 'czr1',
		['price'] = 500000,
		['category'] = 'super',
		['hash'] = 'czr1',
		['shop'] = 'luxury',
	},
	['stingray'] = {
		['name'] = '20 C8 Stingray',
        	['brand'] = 'corvette',
		['model'] = 'stingray',
		['price'] = 70000,
		['category'] = 'sports',
		['hash'] = 'stingray',
		['shop'] = 'luxury',
	},
	---DACIA
	['1310'] = {
		['name'] = '1310',
        	['brand'] = 'DACIA',
		['model'] = '1310',
		['price'] = 520000,
		['category'] = 'sports',
		['hash'] = '1310',
		['shop'] = 'luxury',
	},
	['cutlass'] = {
		['name'] = 'cutlass',
		['brand'] = 'DACIA',
		['model'] = 'cutlass',
		['price'] = 550000,
		['category'] = 'sedans',
		['hash'] = 'cutlass',
		['shop'] = 'luxury',
	},
	['logan'] = {
		['name'] = 'logan',
		['brand'] = 'DACIA',
		['model'] = 'logan',
		['price'] = 20000,
		['category'] = 'sports',
		['hash'] = 'logan',
		['shop'] = 'luxury',
	},
	['sandero'] = {
		['name'] = 'sandero',
		['brand'] = 'DACIA',
		['model'] = 'sandero',
		['price'] = 13500,
		['category'] = 'sports',
		['hash'] = 'sandero',
		['shop'] = 'luxury',
	},
	['stepway'] = {
		['name'] = 'stepway',
		['brand'] = 'DACIA',
		['model'] = 'stepway',
		['price'] = 24000,
		['category'] = 'sports',
		['hash'] = 'stepway',
		['shop'] = 'luxury',
	},
	--DODGE
	['16challenger'] = {
		['name'] = '16 Challenger',
		['brand'] = 'DODGE',
		['model'] = '16challenger',
		['price'] = 19000,
		['category'] = 'muscle',
		['hash'] = '16challenger',
		['shop'] = 'luxury',
	},
	['16charger'] = {
		['name'] = '16 Charger',
		['brand'] = 'DODGE',
		['model'] = '16charger',
		['price'] = 22000,
		['category'] = 'sports',
		['hash'] = '16charger',
		['shop'] = 'luxury',
	},
	['99viper'] = {
		['name'] = '99 Viper',
		['brand'] = 'DODGE',
		['model'] = '99viper',
		['price'] = 22000,
		['category'] = 'sports',
		['hash'] = '99viper',
		['shop'] = 'luxury',
	},
	['chr20'] = {
		['name'] = '20 Charger Hellcat WB',
		['brand'] = 'DODGE',
		['model'] = 'chr20',
		['price'] = 21000,
		['category'] = 'sports',
		['hash'] = 'chr20',
		['shop'] = 'luxury',
	},
	['demon'] = {
		['name'] = '18 Challenger SRT Demon',
		['brand'] = 'DODGE',
		['model'] = 'demon',
		['price'] = 28500,
		['category'] = 'super',
		['hash'] = 'demon',
		['shop'] = 'luxury',
	},
	['raid'] = {
		['name'] = 'Challenger Raid',
		['brand'] = 'DODGE',
		['model'] = 'raid',
		['price'] = 14000,
		['category'] = 'super',
		['hash'] = 'raid',
		['shop'] = 'luxury',
	},
	['ram2500'] = {
		['name'] = 'RAM 2500',
		['brand'] = 'DODGE',
		['model'] = 'ram2500',
		['price'] = 23000,
		['category'] = 'vans',
		['hash'] = 'ram2500',
		['shop'] = 'luxury',
	},
	['srt4'] = {
		['name'] = 'Neon SRT4',
		['brand'] = 'DODGE',
		['model'] = 'srt4',
		['price'] = 30000,
		['category'] = 'sedans',
		['hash'] = 'srt4',
		['shop'] = 'luxury',
	},
	['trx'] = {
		['name'] = 'RAM 1500 Rebel TRX',
		['brand'] = 'DODGE',
		['model'] = 'trx',
		['price'] = 30000,
		['category'] = 'suvs',
		['hash'] = 'trx',
		['shop'] = 'luxury',
	},
	--FERRARI
	['488'] = {							
		['name'] = '488 Spider',
		['brand'] = 'FERRARI',
		['model'] = '488',
		['price'] = 30000,
		['category'] = 'sports',
		['hash'] = '488',
		['shop'] = 'luxury',
	},
	['f430s'] = {
		['name'] = 'f430 Scuderia',
		['brand'] = 'FERRARI',
		['model'] = 'f430s',
		['price'] = 30000,
		['category'] = 'super',
		['hash'] = 'f430s',
		['shop'] = 'luxury',
	},
	['f812'] = {
		['name'] = '18 812 Superfast',
		['brand'] = 'FERRARI',
		['model'] = 'f812',
		['price'] = 30000,
		['category'] = 'super',
		['hash'] = 'f812',
		['shop'] = 'luxury',
	},
	['fct'] = {
		['name'] = '15 California T',
		['brand'] = 'FERRARI',
		['model'] = 'fct',
		['price'] = 38000,
		['category'] = 'sports',
		['hash'] = 'fct',
		['shop'] = 'luxury',
	},
	['fxxk'] = {
		['name'] = 'FXXK Hyb Hyper',
		['brand'] = 'FERRARI',
		['model'] = 'fxxk',
		['price'] = 28000,
		['category'] = 'super',
		['hash'] = 'fxxk',
		['shop'] = 'luxury',
	},
	['laferrari'] = {
		['name'] = 'laferrari',
		['brand'] = 'FERRARI',
		['model'] = 'laferrari',
		['price'] = 5500,
		['category'] = 'super',
		['hash'] = 'laferrari',
		['shop'] = 'luxury',
	},
	['mig'] = {
		['name'] = 'Enzo',
		['brand'] = 'FERRARI',
		['model'] = 'mig',
		['price'] = 12000,
		['category'] = 'sports',
		['hash'] = 'mig',
		['shop'] = 'luxury',
	},
	['yFe458'] = {
		['name'] = 'yFe458',
		['brand'] = 'FERRARI',
		['model'] = 'yFe458',
		['price'] = 2000,
		['category'] = 'sports',
		['hash'] = 'yFe458',
		['shop'] = 'luxury',
	},
	['yFeF12'] = {
		['name'] = 'yFeF12',
		['brand'] = 'FERRARI',
		['model'] = 'yFeF12',
		['price'] = 1900,
		['category'] = 'sports',
		['hash'] = 'yFeF12',
		['shop'] = 'luxury',
	},
	--FORD
	['f150'] = {
		['name'] = '12 F150 SVT Rapor R',
		['brand'] = 'FORD',
		['model'] = 'f150',
		['price'] = 2500,
		['category'] = 'offroad',
		['hash'] = 'f150',
		['shop'] = 'luxury',
	},
	['f15078'] = {
		['name'] = '78 XLT Ranger',
		['brand'] = 'FORD',
		['model'] = 'f15078',
		['price'] = 500000,
		['category'] = 'offroad',
		['hash'] = 'f15078',
		['shop'] = 'luxury',
	},
	['fgt'] = {
		['name'] = '05 GT',
		['brand'] = 'FORD',
		['model'] = 'fgt',
		['price'] = 19000,
		['category'] = 'super',
		['hash'] = 'fgt',
		['shop'] = 'luxury',
	},
	['gt17'] = {
		['name'] = '17 GT',
		['brand'] = 'FORD',
		['model'] = 'gt17',
		['price'] = 320000,
		['category'] = 'super',
		['hash'] = 'gt17',
		['shop'] = 'luxury',
	},
	['mustang2005gt'] = {
		['name'] = 'mustang2005gt',
		['brand'] = 'FORD',
		['model'] = 'mustang2005gt',
		['price'] = 17000,
		['category'] = 'muscle',
		['hash'] = 'mustang2005gt',
		['shop'] = 'luxury',
	},
	['mustang50th'] = {
		['name'] = '15 Mustang GT 50th',
		['brand'] = 'FORD',
		['model'] = 'mustang50th',
		['price'] = 45000,
		['category'] = 'muscle',
		['hash'] = 'mustang50th',
		['shop'] = 'luxury',
	},
	['raptor2017'] = {
		['name'] = '17 Raptor',
		['brand'] = 'FORD',
		['model'] = 'raptor2017',
		['price'] = 16000,
		['category'] = 'offroad',
		['hash'] = 'raptor2017',
		['shop'] = 'luxury',
	},
	['wildtrak'] = {
		['name'] = '21 Bronco Wildtrak',
		['brand'] = 'FORD',
		['model'] = 'wildtrak',
		['price'] = 33500,
		['category'] = 'offroad',
		['hash'] = 'wildtrak',
		['shop'] = 'luxury',
	},
	--HONDA
	['17civict'] = {
		['name'] = '17 Civic Touring',
		['brand'] = 'HONDA',
		['model'] = '17civict',
		['price'] = 28000,
		['category'] = 'sedans',
		['hash'] = '17civict',
		['shop'] = 'luxury',
	},
	['ap2'] = {
		['name'] = 'S2000 AP2',
		['brand'] = 'HONDA',
		['model'] = 'ap2',
		['price'] = 8300,
		['category'] = 'sports',
		['hash'] = 'ap2',
		['shop'] = 'luxury',
	},
	['dragekcivick'] = {
		['name'] = '97 Civic DRAG',
		['brand'] = 'HONDA',
		['model'] = 'dragekcivick',
		['price'] = 20000,
		['category'] = 'sedans',
		['hash'] = 'dragekcivick',
		['shop'] = 'luxury',
	},
	['ep3'] = {
		['name'] = 'ep3',
		['brand'] = 'HONDA',
		['model'] = 'ep3',
		['price'] = 23000,
		['category'] = 'compacts',
		['hash'] = 'ep3',
		['shop'] = 'luxury',
	},
	['fk8'] = {
		['name'] = 'Civic Type R',
		['brand'] = 'HONDA',
		['model'] = 'fk8',
		['price'] = 9999999,
		['category'] = 'compacts',
		['hash'] = 'fk8',
		['shop'] = 'luxury',
	},
	['honcrx91'] = {
		['name'] = '91 CRX',
		['brand'] = 'HONDA',
		['model'] = 'honcrx91',
		['price'] = 15000,
		['category'] = 'sports',
		['hash'] = 'honcrx91',
		['shop'] = 'luxury',
	},
	['na1'] = {
		['name'] = 'NSX R',
		['brand'] = 'HONDA',
		['model'] = 'na1',
		['price'] = 3000,
		['category'] = 'sports',
		['hash'] = 'na1',
		['shop'] = 'luxury',
	},
	--ITALDESIGN]/it18
	['it18'] = {
		['name'] = 'Zerouno',
		['brand'] = 'ITALDESIGN',
		['model'] = 'it18',
		['price'] = 25000,
		['category'] = 'super',
		['hash'] = 'it18',
		['shop'] = 'luxury',
	},
	--jaguar
	['fpacehm'] = {
		['name'] = '17 F-pace',
		['brand'] = 'jaguar',
		['model'] = 'fpacehm',
		['price'] = 5300,
		['category'] = 'suvs',
		['hash'] = 'fpacehm',
		['shop'] = 'luxury',
	},
	--JEEP
	['jeep2012'] = {
		['name'] = '12 Wrangler',
		['brand'] = 'JEEP',
		['model'] = 'jeep2012',
		['price'] = 5300,
		['category'] = 'offroad',
		['hash'] = 'jeep2012',
		['shop'] = 'luxury',
	},
	['jeepreneg'] = {
		['name'] = 'Renegade',
		['brand'] = 'JEEP',
		['model'] = 'jeepreneg',
		['price'] = 35000,
		['category'] = 'suvs',
		['hash'] = 'jeepreneg',
		['shop'] = 'luxury',
	},
	['srt8'] = {
		['name'] = '15 SRT 8',
		['brand'] = 'JEEP',
		['model'] = 'srt8',
		['price'] = 320000,
		['category'] = 'suvs',
		['hash'] = 'srt8',
		['shop'] = 'luxury',
	},
	['trhawk'] = {
		['name'] = '18 Grand Cherokee Trackhawk',
		['brand'] = 'JEEP',
		['model'] = 'trhawk',
		['price'] = 8000,
		['category'] = 'suvs',
		['hash'] = 'trhawk',
		['shop'] = 'luxury',
	},
	--KOENIGSEGG]
	['agerars'] = {
		['name'] = '17 Agera RS',
		['brand'] = 'KOENIGSEGG',
		['model'] = 'agerars',
		['price'] = 50000,
		['category'] = 'super',
		['hash'] = 'agerars',
		['shop'] = 'luxury',
	},
	['regera'] = {
		['name'] = 'Regera',
		['brand'] = 'KOENIGSEGG',
		['model'] = 'regera',
		['price'] = 22000,
		['category'] = 'super',
		['hash'] = 'regera',
		['shop'] = 'luxury',
	},
	--LAMBORGHINI
	['huracanst'] = {
		['name'] = 'Huracan Super Trofeo',
		['brand'] = 'LAMBORGHINI',
		['model'] = 'huracanst',
		['price'] = 7200,
		['category'] = 'super',
		['hash'] = 'huracanst',
		['shop'] = 'luxury',
	},
	['lambose'] = {
		['name'] = 'Sesto Elemento',
		['brand'] = 'LAMBORGHINI',
		['model'] = 'lambose',
		['price'] = 19000,
		['category'] = 'super',
		['hash'] = 'lambose',
		['shop'] = 'luxury',
	},
	['lp670sv'] = {
		['name'] = '09 Murcielago LP 670-4 SV',
		['brand'] = 'LAMBORGHINI',
		['model'] = 'lp670sv',
		['price'] = 31000,
		['category'] = 'super',
		['hash'] = 'lp670sv',
		['shop'] = 'luxury',
	},
	['lp700r'] = {
		['name'] = '13 Aventador LP700-4 Roadster',
		['brand'] = 'LAMBORGHINI',
		['model'] = 'lp700r',
		['price'] = 14000,
		['category'] = 'super',
		['hash'] = 'lp700r',
		['shop'] = 'luxury',
	},
	['svj63'] = {
		['name'] = 'Aventador SVJ',
		['brand'] = 'LAMBORGHINI',
		['model'] = 'svj63',
		['price'] = 28000,
		['category'] = 'super',
		['hash'] = 'svj63',
		['shop'] = 'luxury',
	},
	['urus'] = {
		['name'] = 'Urus',
		['brand'] = 'LAMBORGHINI',
		['model'] = 'urus',
		['price'] = 27000,
		['category'] = 'suvs',
		['hash'] = 'urus',
		['shop'] = 'luxury',
	},
	['veneno'] = {
		['name'] = '13 Veneno LP750-4',
		['brand'] = 'LAMBORGHINI',
		['model'] = 'veneno',
		['price'] = 14000,
		['category'] = 'super',
		['hash'] = 'veneno',
		['shop'] = 'luxury',
	},
	--Landrover
	['lrrr'] = {		
		['name'] = '73 Land Rover Range Rover',
		['brand'] = 'Landrover',
		['model'] = 'lrrr',
		['price'] = 25000,
		['category'] = 'suvs',
		['hash'] = 'lrrr',
		['shop'] = 'luxury',
	},
	--Lexus
	['gs350'] = {		
		['name'] = 'Gs 350',
		['brand'] = 'Lexus',
		['model'] = 'gs350',
		['price'] = 25000,
		['category'] = 'sports',
		['hash'] = 'gs350',
		['shop'] = 'luxury',
	},
	['is350mod'] = {
		['name'] = '14 IS350 MOD',
		['brand'] = 'Lexus',
		['model'] = 'is350mod',
		['price'] = 23500,
		['category'] = 'sports',
		['hash'] = 'is350mod',
		['shop'] = 'luxury',
	},
	['rcf'] = {
		['name'] = '15 RCF',
		['brand'] = 'Lexus',
		['model'] = 'rcf',
		['price'] = 22500,
		['category'] = 'sports',
		['hash'] = 'rcf',
		['shop'] = 'luxury',
	},
	--LOTUS
	['esprit02'] = {
		['name'] = '02 Esprit V8',
		['brand'] = 'LOTUS',
		['model'] = 'esprit02',
		['price'] = 24500,
		['category'] = 'sports',
		['hash'] = 'esprit02',
		['shop'] = 'luxury',
	},
	--LUCIS
	['regalia'] = {
		['name'] = 'Regalia 723',
		['brand'] = 'LUCIS',
		['model'] = 'regalia',
		['price'] = 5000,
		['category'] = 'sedans',
		['hash'] = 'regalia',
		['shop'] = 'luxury',
	},
	--MASERATI
	['levante'] = {
		['name'] = 'levante',
		['brand'] = 'MASERATI',
		['model'] = 'levante',
		['price'] = 8000,
		['category'] = 'suvs',
		['hash'] = 'levante',
		['shop'] = 'luxury',
	},
	--MAZDA
	['84rx7k'] = {
		['name'] = '84 Mazda RX-7 Stanced',
		['brand'] = 'MAZDA',
		['model'] = '84rx7k',
		['price'] = 20000,
		['category'] = 'sportsclassics',
		['hash'] = '84rx7k',
		['shop'] = 'luxury',
	},
	['dragfd'] = {
		['name'] = '02 Mazda RX-7 FD Drag',
		['brand'] = 'MAZDA',
		['model'] = 'dragfd',
		['price'] = 180000,
		['category'] = 'sports',
		['hash'] = 'dragfd',
		['shop'] = 'luxury',
	},
	['fc3s'] = {
		['name'] = 'RX7 FC3S',
		['brand'] = 'MAZDA',
		['model'] = 'fc3s',
		['price'] = 70000,
		['category'] = 'sportsclassics',
		['hash'] = 'fc3s',
		['shop'] = 'luxury',
	},
	['majfd'] = {
		['name'] = 'RX-7 FD',
		['brand'] = 'MAZDA',
		['model'] = 'majfd',
		['price'] = 62500,
		['category'] = 'sports',
		['hash'] = 'majfd',
		['shop'] = 'luxury',
	},
	['miata3'] = {
		['name'] = '89 Mazda Miata NA',
		['brand'] = 'MAZDA',
		['model'] = 'miata3',
		['price'] = 50000,
		['category'] = 'sports',
		['hash'] = 'miata3',
		['shop'] = 'luxury',
	},
	['na6'] = {
		['name'] = 'MX-5 Miata (NA6C)',
		['brand'] = 'MAZDA',
		['model'] = 'na6',
		['price'] = 70000,
		['category'] = 'sports',
		['hash'] = 'na6',
		['shop'] = 'luxury',
	},
	--MCLAREN
	['650s'] = {							
		['name'] = '650S Coupe',
		['brand'] = 'MCLAREN',
		['model'] = '650s',
		['price'] = 200000,
		['category'] = 'sports',
		['hash'] = '650s',
		['shop'] = 'luxury',
	},
	['675lt'] = {							
		['name'] = '16 McLaren 675LT Coupe',
		['brand'] = 'MCLAREN',
		['model'] = '675lt',
		['price'] = 110000,
		['category'] = 'sports',
		['hash'] = '675lt',
		['shop'] = 'luxury',
	},
	['720s'] = {							
		['name'] = '17 McLaren 720S',
		['brand'] = 'MCLAREN',
		['model'] = '720s',
		['price'] = 80000,
		['category'] = 'super',
		['hash'] = '720s',
		['shop'] = 'luxury',
	},
	['gtr96'] = {
		['name'] = '96 McLaren F1 GTR',
		['brand'] = 'MCLAREN',
		['model'] = 'gtr96',
		['price'] = 23500,
		['category'] = 'super',
		['hash'] = 'gtr96',
		['shop'] = 'luxury',
	},
	['mcst'] = {
		['name'] = '20 Speedtail',
		['brand'] = 'MCLAREN',
		['model'] = 'mcst',
		['price'] = 60000,
		['category'] = 'super',
		['hash'] = 'mcst',
		['shop'] = 'luxury',
	},
	['mp412c'] = {
		['name'] = 'MP4-12C',
		['brand'] = 'MCLAREN',
		['model'] = 'mp412c',
		['price'] = 45000,
		['category'] = 'super',
		['hash'] = 'mp412c',
		['shop'] = 'luxury',
	},
	['senna'] = {
		['name'] = '19 Senna',
		['brand'] = 'MCLAREN',
		['model'] = 'senna',
		['price'] = 17000,
		['category'] = 'super',
		['hash'] = 'senna',
		['shop'] = 'luxury',
	},
    --Mercedes
    ['amggtrr20'] = {
		['name'] = '20 AMG GT-R Roadster',
		['brand'] = 'Mercedes',
		['model'] = 'amggtrr20',
		['price'] = 120000,
		['category'] = 'sports',
		['hash'] = 'amggtrr20',
		['shop'] = 'luxury',
	},
    ['g65'] = {
		['name'] = '13 G65 AMG',
		['brand'] = 'Mercedes',
		['model'] = 'g65',
		['price'] = 120000,
		['category'] = 'suvs',
		['hash'] = 'g65',
		['shop'] = 'luxury',
	},
    ['c6320'] = {
		['name'] = '20 Mercedes-AMG C63s',
		['brand'] = 'Mercedes',
		['model'] = 'c6320',
		['price'] = 120000,
		['category'] = 'sedans',
		['hash'] = 'c6320',
		['shop'] = 'luxury',
	},
    ['e400'] = {
		['name'] = '19 E400 Coupe 4matic (C238)',
		['brand'] = 'Mercedes',
		['model'] = 'e400',
		['price'] = 120000,
		['category'] = 'sports',
		['hash'] = 'e400',
		['shop'] = 'luxury',
	},
    ['gl63'] = {
		['name'] = 'GL63 AMG',
		['brand'] = 'Mercedes',
		['model'] = 'gl63',
		['price'] = 120000,
		['category'] = 'suvs',
		['hash'] = 'gl63',
		['shop'] = 'luxury',
	},
    ['mbc63'] = {
		['name'] = '12 C63 AMG Coupe Black Series',
		['brand'] = 'Mercedes',
		['model'] = 'mbc63',
		['price'] = 120000,
		['category'] = 'sports',
		['hash'] = 'mbc63',
		['shop'] = 'luxury',
	},
    ['s500w222'] = {
		['name'] = '14 Mercedes-Benz S500 W222',
		['brand'] = 'Mercedes',
		['model'] = 's500w222',
		['price'] = 120000,
		['category'] = 'sedans',
		['hash'] = 's500w222',
		['shop'] = 'luxury',
	},
    ['sl500'] = {
		['name'] = '95 Mercedes-Benz SL500',
		['brand'] = 'Mercedes',
		['model'] = 'sl500',
		['price'] = 120000,
		['category'] = 'sportsclassics',
		['hash'] = 'sl500',
		['shop'] = 'luxury',
	},
    ['v250'] = {
		['name'] = 'V-class 250 Bluetec LWB',
		['brand'] = 'Mercedes',
		['model'] = 'v250',
		['price'] = 120000,
		['category'] = 'vans',
		['hash'] = 'v250',
		['shop'] = 'luxury',
	},

	--MITSUBISHI
	['cp9a'] = {
		['name'] = 'Lancer Evo VI T.M.E',
		['brand'] = 'MITSUBISHI',
		['model'] = 'cp9a',
		['price'] = 19000,
		['category'] = 'sports',
		['hash'] = 'cp9a',
		['shop'] = 'luxury',
	},
	['fto'] = {
		['name'] = 'FTO GP Version-R',
		['brand'] = 'MITSUBISHI',
		['model'] = 'fto',
		['price'] = 35000,
		['category'] = 'sports',
		['hash'] = 'fto',
		['shop'] = 'luxury',
	},
	--NISSAN
	['180sx'] = {
		['name'] = '180SX Type-X',
		['brand'] = 'NISSAN',
		['model'] = '180sx',
		['price'] = 42250,
		['category'] = 'sports',
		['hash'] = '180sx',
		['shop'] = 'luxury',
	},
	['Safari97'] = {
		['name'] = '97 Patrol Super Safari Y60',
		['brand'] = 'NISSAN',
		['model'] = 'Safari97',
		['price'] = 28500,
		['category'] = 'suvs',
		['hash'] = 'Safari97',
		['shop'] = 'luxury',
	},
	['gtr'] = {
		['name'] = '17 Nissan GTR',
		['brand'] = 'NISSAN',
		['model'] = 'gtr',
		['price'] = 70000,
		['category'] = 'sports',
		['hash'] = 'gtr',
		['shop'] = 'luxury',
	},
	['gtrc'] = {
		['name'] = '17 R35 Nissan GTR Convertible',
		['brand'] = 'NISSAN',
		['model'] = 'gtrc',
		['price'] = 75000,
		['category'] = 'sports',
		['hash'] = 'gtrc',
		['shop'] = 'luxury',
	},
	['maj350'] = {							
		['name'] = 'Fairlady Z Z33',
		['brand'] = 'NISSAN',
		['model'] = 'maj350',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = 'maj350',
		['shop'] = 'luxury',
	},
	['nis15'] = {
		['name'] = 'Silvia S15 Spec-R',
		['brand'] = 'NISSAN',
		['model'] = 'nis15',
		['price'] = 120000,
		['category'] = 'sports',
		['hash'] = 'nis15',
		['shop'] = 'luxury',
	},
	['nissantitan17'] = {
		['name'] = '17 Nissan Titan Warrior',
		['brand'] = 'NISSAN',
		['model'] = 'nissantitan17',
		['price'] = 535000,
		['category'] = 'offroad',
		['hash'] = 'nissantitan17',
		['shop'] = 'luxury',
	},
	['ns350'] = {
		['name'] = 'Nissan 350z Stardast',
		['brand'] = 'NISSAN',
		['model'] = 'ns350',
		['price'] = 90000,
		['category'] = 'sports',
		['hash'] = 'ns350',
		['shop'] = 'luxury',
	},
	['nzp'] = {
		['name'] = 'Nissan 370z Pandem',
		['brand'] = 'NISSAN',
		['model'] = 'nzp',
		['price'] = 95000,
		['category'] = 'sports',
		['hash'] = 'nzp',
		['shop'] = 'luxury',
	},
	['s14'] = {
		['name'] = '98 Nissan Silvia K',
		['brand'] = 'NISSAN',
		['model'] = 's14',
		['price'] = 95000,
		['category'] = 'sports',
		['hash'] = 's14',
		['shop'] = 'luxury',
	},
	['skyline'] = {
		['name'] = 'Nissan Skyline GT-R BNR34',
		['brand'] = 'NISSAN',
		['model'] = 'skyline',
		['price'] = 95000,
		['category'] = 'sports',
		['hash'] = 'skyline',
		['shop'] = 'luxury',
	},
	['z32'] = {
		['name'] = '300ZX Z32',
		['brand'] = 'NISSAN',
		['model'] = 'z32',
		['price'] = 95000,
		['category'] = 'sports',
		['hash'] = 'z32',
		['shop'] = 'luxury',
	},
	--PEUGEOT
	['yPG205t16'] = {
		['name'] = 'yPG205t16',
		['brand'] = 'PEUGEOT',
		['model'] = 'yPG205t16',
		['price'] = 95000,
		['category'] = 'sports',
		['hash'] = 'yPG205t16',
		['shop'] = 'luxury',
	},
	--PORSCHE
	['718caymans'] = {
		['name'] = 'Porsche 718 Cayman S',
		['brand'] = 'PORSCHE',
		['model'] = '718caymans',
		['price'] = 95000,
		['category'] = 'super',
		['hash'] = '718caymans',
		['shop'] = 'luxury',
	},
	['cgt'] = {
		['name'] = '03 Porsche Carrera GT (980)',
		['brand'] = 'PORSCHE',
		['model'] = 'cgt',
		['price'] = 95000,
		['category'] = 'super',
		['hash'] = 'cgt',
		['shop'] = 'luxury',
	},
	['maj935'] = {
		['name'] = '78 Porsche 935 Moby Dick',
		['brand'] = 'PORSCHE',
		['model'] = 'maj935',
		['price'] = 95000,
		['category'] = 'sportsclassics',
		['hash'] = 'maj935',
		['shop'] = 'luxury',
	},
	['pcs18'] = {
		['name'] = '18 Porsche Cayenne S',
		['brand'] = 'PORSCHE',
		['model'] = 'pcs18',
		['price'] = 21000,
		['category'] = 'suvs',
		['hash'] = 'pcs18',
		['shop'] = 'luxury',
	},
	['pm19'] = {
		['name'] = '19 Porsche Macan Turbo',
		['brand'] = 'PORSCHE',
		['model'] = 'pm19',
		['price'] = 13000,
		['category'] = 'super',
		['hash'] = 'pm19',
		['shop'] = 'luxury',
	},
	['taycan'] = {
		['name'] = '20 Porsche Taycan Turbo S',
		['brand'] = 'PORSCHE',
		['model'] = 'taycan',
		['price'] = 15000,
		['category'] = 'sports',
		['hash'] = 'taycan',
		['shop'] = 'luxury',
	},
	--Rangerover
	['rrevoque'] = {
		['name'] = 'Range Rover Evoque',
		['brand'] = 'Rangerover',
		['model'] = 'rrevoque',
		['price'] = 70000,
		['category'] = 'suvs',
		['hash'] = 'rrevoque',
		['shop'] = 'luxury',
	},
	['rrst'] = {
		['name'] = 'Range Rover Vogue Startech',
		['brand'] = 'Rangerover',
		['model'] = 'rrst',
		['price'] = 40000,
		['category'] = 'suvs',
		['hash'] = 'rrst',
		['shop'] = 'luxury',
	},
	['rsvr16'] = {
		['name'] = '16 Range Rover Sport SVR',
		['brand'] = 'Rangerover',
		['model'] = 'rsvr16',
		['price'] = 65000,
		['category'] = 'suvs',
		['hash'] = 'rsvr16',
		['shop'] = 'luxury',
	},
	--RENAULT
	['twingo'] = {
		['name'] = 'twingo',
		['brand'] = 'RENAULT',
		['model'] = 'twingo',
		['price'] = 20000,
		['category'] = 'sportsclassics',
		['hash'] = 'twingo',
		['shop'] = 'luxury',
	},
	--ROLLSROYCE
	['dawnonyx'] = {
		['name'] = '16 Rolls-Royce Dawn Onyx',
		['brand'] = 'ROLLSROYCE',
		['model'] = 'dawnonyx',
		['price'] = 20000,
		['category'] = 'coupes',
		['hash'] = 'dawnonyx',
		['shop'] = 'luxury',
	},
	['rculi'] = {
		['name'] = 'Rolls Royce Cullinan',
		['brand'] = 'ROLLSROYCE',
		['model'] = 'rculi',
		['price'] = 29000,
		['category'] = 'suvs',
		['hash'] = 'rculi',
		['shop'] = 'luxury',
	},
	['rrphantom'] = {
		['name'] = '18 Rolls-Royce Phantom VIII',
		['brand'] = 'ROLLSROYCE',
		['model'] = 'rrphantom',
		['price'] = 50000,
		['category'] = 'sedans',
		['hash'] = 'rrphantom',
		['shop'] = 'luxury',
	},
	['wraith'] = {
		['name'] = 'Rolls-Royce Wraith',
		['brand'] = 'ROLLSROYCE',
		['model'] = 'wraith',
		['price'] = 23000,
		['category'] = 'coupes',
		['hash'] = 'wraith',
		['shop'] = 'luxury',
	},
    --SUBARU
    ['subisti08'] = {
		['name'] = '08 Subaru WRX STi',
		['brand'] = 'SUBARU',
		['model'] = 'subisti08',
		['price'] = 23000,
		['category'] = 'sports',
		['hash'] = 'subisti08',
		['shop'] = 'luxury',
	},
    ['subwrx'] = {
		['name'] = '04 Subaru Impreza WRX STI',
		['brand'] = 'SUBARU',
		['model'] = 'subwrx',
		['price'] = 23000,
		['category'] = 'sports',
		['hash'] = 'subwrx',
		['shop'] = 'luxury',
	},
    ['svx'] = {
		['name'] = '96 Subaru Alcyone SVX',
		['brand'] = 'SUBARU',
		['model'] = 'svx',
		['price'] = 23000,
		['category'] = 'coupes',
		['hash'] = 'svx',
		['shop'] = 'luxury',
	},
	--suzuki
	['gsxr19'] = {
		['name'] = '19 Suzuki GSX-R1000R',
		['brand'] = 'suzuki',
		['model'] = 'gsxr19',
		['price'] = 26500,
		['category'] = 'motorcycle',
		['hash'] = 'gsxr19',
		['shop'] = 'luxury',
	},
	['katana19'] = {
		['name'] = '19 Suzuki Katana',
		['brand'] = 'suzuki',
		['model'] = 'katana19',
		['price'] = 30000,
		['category'] = 'motorcycle',
		['hash'] = 'katana19',
		['shop'] = 'luxury',
	},
	--Tesla
	['models'] = {
		['name'] = '16 Tesla Model S P90D',
		['brand'] = 'Tesla',
		['model'] = 'models',
		['price'] = 90000,
		['category'] = 'sedans',
		['hash'] = 'models',
		['shop'] = 'luxury',
	},
	['p90d'] = {
		['name'] = 'Tesla Model X Unplugged Performance',
		['brand'] = 'Tesla',
		['model'] = 'p90d',
		['price'] = 17000,
		['category'] = 'sedans',
		['hash'] = 'p90d',
		['shop'] = 'luxury',
	},
	['teslapd'] = {
		['name'] = '17 Tesla Model S Prior design',
		['brand'] = 'Tesla',
		['model'] = 'teslapd',
		['price'] = 33000,
		['category'] = 'sedans',
		['hash'] = 'teslapd',
		['shop'] = 'luxury',
	},
	['teslax'] = {
		['name'] = '16 Tesla Model X P90D',
		['brand'] = 'Tesla',
		['model'] = 'teslax',
		['price'] = 40000,
		['category'] = 'compacts',
		['hash'] = 'teslax',
		['shop'] = 'luxury',
	},
	['tmodel'] = {
		['name'] = '18 Tesla Model 3',
		['brand'] = 'Tesla',
		['model'] = 'tmodel',
		['price'] = 24500,
		['category'] = 'super',
		['hash'] = 'tmodel',
		['shop'] = 'luxury',
	},
	['tr22'] = {							
		['name'] = '20 Tesla Roadster',
		['brand'] = 'Tesla',
		['model'] = 'tr22',
		['price'] = 80000,
		['category'] = 'muscle',
		['hash'] = 'tr22',
		['shop'] = 'luxury',
	},
	--TOYOTA
	['ae86'] = {							
		['name'] = 'ae86',
		['brand'] = 'TOYOTA',
		['model'] = 'ae86',
		['price'] = 30000,
		['category'] = 'sports',
		['hash'] = 'ae86',
		['shop'] = 'luxury',
	},
	['cam8tun'] = {
		['name'] = '18 Toyota Camry XSE',
		['brand'] = 'TOYOTA',
		['model'] = 'cam8tun',
		['price'] = 39500,
		['category'] = 'sports',
		['hash'] = 'cam8tun',
		['shop'] = 'luxury',
	},
	['mk2100'] = {
		['name'] = 'Toyota Mark II JZX100',
		['brand'] = 'TOYOTA',
		['model'] = 'mk2100',
		['price'] = 22000,
		['category'] = 'sedans',
		['hash'] = 'mk2100',
		['shop'] = 'luxury',
	},
	['toysupmk4'] = {
		['name'] = '98 Toyota Supra Turbo (A80)',
		['brand'] = 'TOYOTA',
		['model'] = 'toysupmk4',
		['price'] = 21000,
		['category'] = 'sports',
		['hash'] = 'toysupmk4',
		['shop'] = 'luxury',
	},
	['vxr'] = {
		['name'] = '16 Toyota Land Cruiser VXR',
		['brand'] = 'TOYOTA',
		['model'] = 'vxr',
		['price'] = 21000,
		['category'] = 'suvs',
		['hash'] = 'vxr',
		['shop'] = 'luxury',
	},
	--VOLKSWAGEN
	['amarok'] = {
		['name'] = 'amarok',
		['brand'] = 'VOLKSWAGEN',
		['model'] = 'amarok',
		['price'] = 13000,
		['category'] = 'vans',
		['hash'] = 'amarok',
		['shop'] = 'luxury',
	},
	['golf8gti'] = {
		['name'] = '15 Volkswagen Golf GTI MK7',
		['brand'] = 'VOLKSWAGEN',
		['model'] = 'golf8gti',
		['price'] = 19500,
		['category'] = 'sports',
		['hash'] = 'golf8gti',
		['shop'] = 'luxury',
	},
	['golfgti7'] = {
		['name'] = 'golfgti7',
		['brand'] = 'VOLKSWAGEN',
		['model'] = 'golfgti7',
		['price'] = 55000,
		['category'] = 'sports',
		['hash'] = 'golfgti7',
		['shop'] = 'luxury',
	},
	['vwr'] = { 	 	
		['name'] = 'vwr',
		['brand'] = 'VOLKSWAGEN',
		['model'] = 'vwr',
		['price'] = 345000,
		['category'] = 'compacts',
		['hash'] = 'vwr',
		['shop'] = 'luxury',
	},
    ['passat'] = { 	 	
		['name'] = 'passat',
		['brand'] = 'VOLKSWAGEN',
		['model'] = 'passat',
		['price'] = 345000,
		['category'] = 'super',
		['hash'] = 'passat',
		['shop'] = 'luxury',
	},
	---VOLVO
	['xc90'] = {
		['name'] = 'Volvo XC90 T8',
		['brand'] = 'VOLVO',
		['price'] = 9000,
		['category'] = 'suvs',
		['model'] = 'xc90',
		['hash'] = 'xc90',
		['shop'] = 'luxury',
	},
	--WMOTORS
	['lykan'] = {
		['name'] = 'W-Motors Lykan HyperSport',
		['brand'] = 'WMOTORS',
		['price'] = 15500,
		['category'] = 'super',
		['model'] = 'lykan',
		['hash'] = 'lykan',
		['shop'] = 'luxury',
	},
	['wmfenyr'] = {
		['name'] = 'W-Motors Fenyr Supersport',
		['brand'] = 'WMOTORS',
		['price'] = 75000,
		['category'] = 'super',
		['model'] = 'wmfenyr',
		['hash'] = 'wmfenyr',
		['shop'] = 'luxury',
	},
